package theme

import "github.com/gdamore/tcell/v2"

type ColorScheme struct {
	WindowBackground    tcell.Style
	WindowFrameActive   tcell.Style
	WindowFrameInactive tcell.Style
	WindowTitle         tcell.Style
	WindowShadow        tcell.Style
	DesktopBackground   tcell.Style
	DialogBackground    tcell.Style
	DialogFrame         tcell.Style
	ButtonNormal        tcell.Style
	ButtonDefault       tcell.Style
	ButtonShadow        tcell.Style
	ButtonShortcut      tcell.Style
	InputNormal         tcell.Style
	InputSelection      tcell.Style
	LabelNormal         tcell.Style
	LabelHighlight      tcell.Style
	LabelShortcut       tcell.Style
	CheckBoxNormal      tcell.Style
	CheckBoxSelected    tcell.Style
	RadioButtonNormal   tcell.Style
	RadioButtonSelected tcell.Style
	ClusterDisabled     tcell.Style
	ListNormal          tcell.Style
	ListSelected        tcell.Style
	ListFocused         tcell.Style
	ScrollBar           tcell.Style
	ScrollThumb         tcell.Style
	MenuNormal          tcell.Style
	MenuShortcut        tcell.Style
	MenuSelected        tcell.Style
	MenuDisabled        tcell.Style
	StatusNormal        tcell.Style
	StatusShortcut      tcell.Style
	StatusSelected      tcell.Style
	MemoNormal          tcell.Style
	MemoSelected        tcell.Style
	HistoryArrow        tcell.Style
	HistorySides        tcell.Style
	ColorSelectorNormal tcell.Style
	ColorSelectorCursor tcell.Style
	ColorDisplayText    tcell.Style
	OutlineNormal    tcell.Style
	OutlineFocused   tcell.Style
	OutlineSelected  tcell.Style
	OutlineCollapsed tcell.Style

	// Markdown viewer
	MarkdownNormal      tcell.Style
	MarkdownH1          tcell.Style
	MarkdownH2          tcell.Style
	MarkdownH3          tcell.Style
	MarkdownH4          tcell.Style
	MarkdownH5          tcell.Style
	MarkdownH6          tcell.Style
	MarkdownBold        tcell.Style
	MarkdownItalic      tcell.Style
	MarkdownBoldItalic  tcell.Style
	MarkdownCode        tcell.Style
	MarkdownCodeBlock   tcell.Style
	MarkdownBlockquote  tcell.Style
	MarkdownLink        tcell.Style
	MarkdownHRule       tcell.Style
	MarkdownListMarker  tcell.Style
	MarkdownTableBorder tcell.Style
	MarkdownDefTerm     tcell.Style
}
